Models/ErrorViewModel.cs
namespace cp202201_voto_MVC_v1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/UsuarioModel.cs
    namespace cp202201_voto_MVC_v1.Models
{
    public class UsuarioModel
    {
        public int Id { get; set; }
        public string? Paterno { get; set; }
        public string? Materno { get; set; }
        public string? Nombres { get; set; }
        public string? NumeroDocumento { get; set; }
        public string? Telefono { get; set; }
        public string? Dirección { get; set; }
        public DateTime? FechaNacimiento { get; set; }
        public string? Password { get; set; }
        public string? Correo { get; set; }
        public bool? EsAdmin { get; set; }
    }
}

Areas/Administrador/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace cp202201_voto_MVC_v1.Areas.Administrador.Controllers
{
    [Area("Administrador")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CrearProcesoVotacion()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using cp202201_voto_MVC_v1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace cp202201_voto_MVC_v1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        
    }
}

Controllers/SecurityController.cs
using cp202201_voto_MVC_v1.Models;
using cp202201_voto_MVC_v1.Service;
using Microsoft.AspNetCore.Mvc;

namespace cp202201_voto_MVC_v1.Controllers
{
    public class SecurityController : Controller
    {
        public async Task <IActionResult> signUp()
        {
            //var usuarios = await UsuarioService.Post();

            return View();
        }

        public IActionResult login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Autenticarse(IFormCollection form)
        {
            var correo = form["correo"];
            var clave = form["clave"];

            //Enviar al endpoint para validar si el correo y clave existe


            return RedirectToAction("RegistroVotacion", "Usuario");
        }

        [HttpPost]
        public async Task<IActionResult> login(IFormCollection form)
        {
            var usuario = new UsuarioModel();
            usuario.Paterno = form["paterno"];
            usuario.Materno = form["materno"];
            usuario.Nombres = form["nombres"];
            usuario.Correo = form["correo"];
            usuario.NumeroDocumento = form["dni"];
            usuario.Telefono = form["telefono"];
            usuario.FechaNacimiento = Convert.ToDateTime(form["fechaNacimiento"]);
            usuario.Dirección = form["direccion"];
            usuario.Password = form["clave"];
            //var paterno = form["paterno"];
            var result = await UsuarioService.Create(usuario);

            if (result>0)
                return RedirectToAction("login");
            else
                return RedirectToAction("signUp");

        }
    }
}

Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;

namespace cp202201_voto_MVC_v1.Controllers
{
    public class UsuarioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult RegistroVotacion()
        {
            return View();
        }
    }
}

Controllers/VoterController.cs
using Microsoft.AspNetCore.Mvc;

namespace cp202201_voto_MVC_v1.Controllers
{
    public class VoterController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult Results()
        {
            return View();
        }

        public IActionResult newVote()
        {
            return View();
        }

        public IActionResult createPeriod()
        {
            return View();
        }


    }
}

Controllers/WeatherForecastController.cs
using Microsoft.AspNetCore.Mvc;

namespace cp202201_voto_API_v1.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : ControllerBase
    {
        private static readonly string[] Summaries = new[]
        {
        "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
    };

        private readonly ILogger<WeatherForecastController> _logger;

        public WeatherForecastController(ILogger<WeatherForecastController> logger)
        {
            _logger = logger;
        }

        [HttpGet(Name = "GetWeatherForecast")]
        public IEnumerable<WeatherForecast> Get()
        {
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = Random.Shared.Next(-20, 55),
                Summary = Summaries[Random.Shared.Next(Summaries.Length)]
            })
            .ToArray();
        }
    }
}

Areas/Administrador/Views/Home/CrearProcesoVotacion.cshtml
<h3>Aquí crearán los procesos de votación</h3>

Areas/Administrador/Views/Home/Index.cshtml
<h1>Aquí será el dashboard del Admin</h1>

Areas/Administrador/Views/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema Votación ADMINISTRADOR</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/cp202201_voto_MVC_v1.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Sistema de Votación - Administrador</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-area="Administrador" asp-controller="Home" asp-action="CrearProcesoVotacion">Crear proceso de votación</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/voter/newVote">Elegir Candidatos</a>
                        </li>
                      @*  <li class="nav-item">
                            <a class="nav-link" href="/voter/createPeriod">Crear nueva votación</a>
                        </li>*@

                    </ul>
                    <div class=" align-center">
                        <span class="pe-3">
                            Votante Apellido
                        </span>
                        <button class="btn btn-outline-primary" type="submit"
                                onclick="window.location.href='/security/login'">
                        Cerrar Sesión</button>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="d-flex flex-column min-vh-100 pb-3">
            <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
            @RenderBody()
        </main>
    </div>

    <footer class="mt-auto border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Sistema de votación - <a asp-area="" asp-controller="Voter" asp-action="Index">Inicio</a>
        </div>
    </footer>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Security/login.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <style>
        body {
            margin: 0;
            padding: 0;
            background-color: #ACACAC;
            height: 100vh;
        }

        #login .container #login-row #login-column #login-box {
            margin-top: 120px;
            max-width: 470px;
            height: 400px;
            border: 12px solid #F7F7F7;
            background-color: #FFFFFF;
        }

            #login .container #login-row #login-column #login-box #login-form {
                padding: 20px;
            }

                #login .container #login-row #login-column #login-box #login-form #register-link {
                    margin-top: -85px;
                }
    </style>
</head>
<body>

    <div id="login">
        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <div id="login-box" class="col-md-12">
                        <h3 class="text-center text-info">Iniciar sesión</h3>
                         <form method="post" id="loginForm" action="~/Security/Autenticarse">
                            <div class="input-contenedor">
                                <label for="Correo" class="text-info">Correo:</label><br>
                                <input type="email" name="email" id="iemail" class="form-control placeholder = "Email" />
                            </div>
                            <div class="input-contenedor">
                                <label for="NumeroDocumento" class="text-info">Numero de Documento:</label><br>
                                <input type="text" name="dni" id="itext" class="form-control placeholder = "DNI" />
                            </div>
                            <div class="input-contenedor">
                                <label for="password" class="text-center text-info">Contraseña:</label><br>
                                <input type="password" name="clave" id="ipass" class="form-control placeholder = "Contraseña" />
                            </div>
                            <div class="form-group">
                                <label for="remember-me" class="text-center text-info"><span>Recordar</span> <span><input id="remember-me" name="remember-me" type="checkbox"></span></label><br>
                                <input type="submit" name="submit" class="text-center btn btn-info btn-md" value="Ingresar">
                                <p>¿No tienes cuenta?<a class="link" href="/security/signUp">Registrate</a></p>
                            </div>
                            </form>
                        <div style="color:red;">@ViewBag.message</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

Views/Security/signUp.cshtml
@{
    Layout = null;
    @model UsuarioModel
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Registro - Voto electrónico</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PC2_Views.styles.css" asp-append-version="true" />
</head>
<body>
<section class="vh-100" style="background-color: #F8F9FA;">

   <div class="container h-100">

        <div class="d-flex flex-column justify-content-center align-items-center h-100">
            <div class="bg-white border w-75 rounded-5 p-5">

                <div class="d-flex">
                    <div class="w-100">
                        <h1 class="mb-4 fw-bold text-center">Crear Cuenta</h1>
                    </div>

                </div>
                <form method="post" id="loginForm" action="~/Security/Login">
                    <div class="row">                        
                         <div class="form-group mb-3 col-lg-4">
                            <label class="label">Apellido Paterno</label> <input class="form-control" placeholder="Apellido Paterno" required="" name="paterno" id="txtLastname">
                        </div>
                         <div class="form-group mb-3 col-lg-4">
                            <label class="label">Apellido Materno</label> <input class="form-control" placeholder="Apellido Materno" required="" name="materno" id="txtLastname">
                        </div>
                         <div class="form-group mb-3 col-lg-4">
                            <label class="label">Nombres</label> <input class="form-control" placeholder="Ingrese nombres" required="" name="nombres" id="txtName">
                        </div>
                    </div>
                    <div class="row"> 
                        <div class="form-group mb-3 col-lg-6">
                            <label class="label">Correo electrónico</label> <input class="form-control" placeholder="Ingrese correo electrónico" required="" name="correo" id="txtEmail">

                        </div>
                         <div class="form-group mb-3 col-lg-6">
                            <label class="label">DNI</label> <input class="form-control" placeholder="Ingrese DNI" required="" name="dni" id="txtDNI">

                        </div>
                    </div>
                    <div class="row"> 
                        <div class="form-group mb-3 col-lg-6">
                            <label class="label">Teléfono</label> <input class="form-control" placeholder="Ingrese teléfono" required="" name="telefono" id="txtPhone">

                        </div>
                         <div class="form-group mb-3 col-lg-6">
                            <label class="label">Fecha de nacimiento</label> <input class="form-control" placeholder="Ingrese fecha de nacimiento" required="" name="fechaNacimiento" id="txtBirthdate">

                        </div>
                    </div>
                    <div class="row"> 
                        <div class="form-group mb-3 col-lg-6">
                            <label class="label">Dirección</label> <input class="form-control" placeholder="Ingrese dirección" required="" name="direccion" id="txtAddress">

                        </div>
                         <div class="form-group mb-3 col-lg-6">
                            <label class="label">Contraseña</label> <input class="form-control" placeholder="Ingrese contraseña" required="" name="clave" id="txtPassword">

                        </div>
                    </div>
                    <div class="form-group">
                        <button type="submit" id="btnSubmit" class="form-control btn btn-primary">
                            Registrar
                        </button>
                    </div>

                </form>
                 <div class="pt-4 text-gray-400 ">¿Ya tienes cuenta?
								<a href="/security/login" class="link-primary"> Inicia sesión</a></div>
            </div>

        </div>
    </div>
</section>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema Votación</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/cp202201_voto_MVC_v1.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Sistema de Votación</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/voter/index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/voter/newVote">Votar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/voter/createPeriod">Crear nueva votación</a>
                        </li>

                    </ul>
                    <div class=" align-center">
                        <span class="pe-3">
                            Votante Apellido
                        </span>
                        <button class="btn btn-outline-primary" type="submit"
                                onclick="window.location.href='/security/login'">
                        Cerrar Sesión</button>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="d-flex flex-column min-vh-100 pb-3">
            <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
            @RenderBody()
        </main>
    </div>

    <footer class="mt-auto border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Sistema de votación - <a asp-area="" asp-controller="Voter" asp-action="Index">Inicio</a>
        </div>
    </footer>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Usuario/RegistroVotacion.cshtml
<h1>Aquí crearán su form de registro de votación</h1>

Views/Voter/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="row d-flex flex-row mt-5"> 

   <div class="col-lg-6 card text-dark bg-light mb-3 p-0">
        <div class="card-header fs-5 fw-bold">En curso</div>
        <div class="card-body">
            <div class="row pb-4">
                <div class="col-9">
                    <span>Elección de alcaldes</span><br><span class="fw-light">Periodo 2022-1</span>
                </div>
                <div class="col-3 text-center">
                    <a href="#" class="btn btn-primary">Ingresar</a>


                </div>
            </div>

            <div class="row">
                <div class="col-9">
                    <span>Elección de congresistas</span><br><span class="fw-light">Periodo 2022-1</span>
                </div>
                <div class="col-3 text-center">
                    <a href="#" class="btn btn-primary">Ingresar</a>


                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-1 "> </div>
       <div class="col-lg-5 card text-dark bg-light mb-3 p-0">
        <div class="card-header fs-5 fw-bold">Culminadas</div>
        <div class="card-body">
            <div class="row pb-4">
                <div class="col-9">
                    <span>Elección de presidentes</span><br><span class="fw-light">Periodo 2021</span>
                </div>
                <div class="col-3 text-center">
                    <a href="#" class="btn btn-primary">Resultados</a>


                </div>
            </div>

            <div class="row">
                <div class="col-9">
                    <span>Elección de presidentes</span><br><span class="fw-light">Periodo 2016</span>
                </div>
                <div class="col-3 text-center">
                    <a href="#" class="btn btn-primary">Resultados</a>


                </div>
            </div>
        </div>
    
    </div>
</div>           

Views/Voter/newVote.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h4>Votación - Elección alcaldes</h4>
<div class="col-lg-1 "> </div>
        <div class="col-lg-6 card text-dark bg-light mb-3 p-2">
        <div class="card-header fs-5 fw-bold">Candidato</div>
        <div class="card-body">
            <div class="form-check">
                <input class="form-check-input" type="radio" name="Radios" id="idcand1" value="option1" checked>
                <label class="form-check-label" for="idcand1">
                    Manuel Mala
                </label>
                <small class="form-text text-muted" for="idcand1">
                    Partido: Unidos
                </small>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="Radios" id="idcand2" value="option2" checked>
                <label class="form-check-label" for="idcand2">
                    Viviana Lorenzo
                </label>
                <small class="form-text text-muted" for="idcand2">
                    Partido: Victoria
                </small>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="Radios" id="idcand3" value="option3" checked>
                <label class="form-check-label" for="idcand3">
                    Mariano Gonzales
                </label>
                <small class="form-text text-muted" for="idcand3">
                    Partido: Juntos Podemos
                </small>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="Radios" id="idcand4" value="option4" checked>
                <label class="form-check-label" for="idcand4">
                    Samir Mendez
                </label>
                <small class="form-text text-muted" for="idcand4">
                    Partido: Unidoss
                </small>
            </div>
            <div class="text-end col pe-4 pb-3">
                    <button class="btn btn-primary" type="button">Seleccionar</button>
            </div>
        </div>
</div>